[theme]
primaryColor = "#3498db"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#2c3e50"
font = "sans serif"

[server]
maxUploadSize = 200
maxMessageSize = 200
enableCORS = false
enableXsrfProtection = true
enableWebsocketCompression = true

[browser]
gatherUsageStats = false

[client]
caching = true
displayEnabled = true
showErrorDetails = true

[global]
suppressDeprecationWarnings = true
showWarningOnDirectExecution = false
unitTest = false
